services:

  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:Z
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    command: pnpm dev --host